title: <p align="center"> Jeyashree Murugappan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/JeyashreeMurugappan">GitHub</a>
  
  <br>   
  I'm working on Data Science
  Also handing the Big Data from real-time Ad call data.
  <br>
  </p>



theme: jekyll-theme-minimal